using AutoRepairCRM.Core.Models.Customer;
using AutoRepairCRM.Core.Models.Employee;
using AutoRepairCRM.Database.Data.Models.Account;

namespace AutoRepairCRM.Core.Contracts;

public interface IAccountService
{
    /// <summary>
    /// Creates a user for a registered customer.
    /// </summary>
    /// <param name="model">CustomerInputModel object.</param>
    /// <returns>ApplicationUser object created by the model with password generated by the first name phone number and '.' at the end.</returns>
    Task<ApplicationUser?> CreateCustomer(CustomerInputModel model);
    
    /// <summary>
    /// Creates a user for a registered employee.
    /// </summary>
    /// <param name="model">EmployeeInputModel object.</param>
    /// <returns>ApplicationUser object created by the model with password generated by the first name phone number and '.' at the end.</returns>
    Task<ApplicationUser?> CreateEmployee(EmployeeInputModel model);

    /// <summary>
    /// Gets all user roles.
    /// </summary>
    /// <param name="user">ApplicationUser object.</param>
    /// <returns>IEnumerable of strings. Each string is one role.</returns>
    Task<IEnumerable<string>> GetRolesForUser(ApplicationUser user);

    /// <summary>
    /// Makes ApplicationUser account inactive and inaccessible.
    /// </summary>
    /// <param name="id">String the id of the user.</param>
    /// <returns>True if deactivated successfully, otherwise false.</returns>
    Task<bool> Deactivate(string id);
}